### ISSUE TITLE
 useMediaQuery returns updated value after 15px

### ISSUE THREAD

**Issue by Gilbishkosma** [heyitsarpit/react-hooks-library#19]
i am using the  **useMediaQuery** hook.
My code:
```
   const isDesktopScreen = useMediaQuery('(min-width: 1552px)')
```

the **isDesktopScreen** return false at **1537px** instead of **1552px**.
The useMediaQuery returns updated value after **15px is decreased or increased.**

**Comment by heyitsarpit** [comment]
Also found this issue. - [Chrome Device Mode Emulation Media Queries Not Working]( https://stackoverflow.com/questions/26888751/chrome-device-mode-emulation-media-queries-not-working)

`<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />` might be your fix.
