### ISSUE TITLE
[hooks] useEffectAfterMount does not return clean up function

### ISSUE THREAD

**Issue by ArtemGolovko** [heyitsarpit/react-hooks-library#24]
`useEffectAfterMount` does not currently return clean up function, i.e. user passed clean up function will not run.

Solution - return user passed clean up function.

**Comment by heyitsarpit** [comment]
@ArtemGolovko Thanks for pointing this out, the new release [v0.4.2](https://github.com/heyitsarpit/react-hooks-library/releases/tag/v0.4.2) , you can just return a cleanup function from the hook like you normally do with `useEffect`.

this code will work now.

```ts
  useEffectAfterMount(() => {
    setSecondEffect(true)

    return () => console.log('run cleanup')
  }, [count])
```
